### ISSUE TITLE
Create email-validation template

### ISSUE THREAD

**Issue by leal32b** [leal32b/webapi-nodejs#10]
### Context:
In order to send messages from the webapi it is needed to implement a communication module

### To do:
- TDD: create tests
- Create template for e-mail `email-validation` in `modules/communication/0.domain/templates`

### Definition of done:
- `email-validation` template created
- All tests passing

**Comment by yazaldefilimone** [comment]
I created pull request at  #28

**Comment by leal32b** [comment]
Hey @yazaldefilimonepinto !
Actually the `To do` is a little confusing, I'm sorry 😅
What is needed here is to create a template to be used to send the confirmation email when the user creates a new account.
`email-validation`: the e-mail sent to confirm that the e-mail used by the user is valid (will be used here: `src/modules/communication/1.application/use-cases/send-email-validation-email-use-case.ts:31`)
Thanks for the contribution, anyway 😉
